name: ftxui-starter
version: '1.0'
summary: A simple starter project for the FTXUI library.
description: A simple starter project for the FTXUI library.

grade: stable
confinement: strict
base: core18

apps:
  ftxui-starter:
    command: ftxui-starter

parts:
  ftxui-starter:
    plugin: cmake
    source: https://github.com/ArthurSonzogni/ftxui-starter
    source-type: git
    source-depth: 1
    build-snaps: [cmake/stable]
    build-packages: [clang]
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL"
      - "-DCMAKE_BUILD_TYPE=Release"

passthrough:
  title: ftxui-starter
  license: MIT
